FROM ubuntu

RUN apt-get update
RUN apt-get install gcc
RUN apt-get install cmake
RUN apt-get install build-essential
RUN apt-get install git
RUN git clone https://github.com/Kitware/CMake.git
RUN git clone https://github.com/DJTakushi/dockerDemo.git
